import Head from 'next/head'
import Carrousel from "@/components/Carrousel";
import ResponsiveAppBar from "@/components/ResponsiveAppBar";


export default function Home() {
    return (
        <>
            <Head>
                <title>Arts et Services 3D</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <ResponsiveAppBar/>

            <Carrousel/>
        </>
    )
}
